# Generated by Django 2.2 on 2020-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[(11, 'Department'), (12, 'Institute/College'), (13, 'University')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub_category',
            field=models.CharField(choices=[(11, 'Admission'), (12, 'Finance'), (13, 'Examination'), (21, 'Lecture TimeTable/ Learning'), (22, 'Paper Re-evaluation'), (31, 'Others')], max_length=30, null=True),
        ),
    ]
